//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Account_Right_Detail = new HashSet<Account_Right_Detail>();
            this.Files = new HashSet<File>();
            this.Important_Documentary = new HashSet<Important_Documentary>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public Nullable<int> Role { get; set; }
        public string NVID { get; set; }
        public bool CDVT { get; set; }
        public bool TCLD { get; set; }
        public bool BGD { get; set; }
        public bool DK { get; set; }
        public bool KCS { get; set; }
        public bool PXKT { get; set; }
        public bool PXDL { get; set; }
        public bool PXVT { get; set; }
        public bool PXCBT { get; set; }
        public bool PXPV { get; set; }
        public bool PXDS { get; set; }
        public bool PXCDM { get; set; }
        public bool PXTGQLM { get; set; }
        public bool PXXD { get; set; }
        public bool AT { get; set; }
        public bool KCM { get; set; }
        public bool ADMIN { get; set; }
        public Nullable<bool> PXCKSC { get; set; }
        public string token { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual ICollection<Account_Right_Detail> Account_Right_Detail { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Important_Documentary> Important_Documentary { get; set; }
    }
}
