//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigMaintainEquipment
    {
        public int supplyDocumentaryEquipmentId { get; set; }
        public int documentary_big_maintain_id { get; set; }
        public string supply_id { get; set; }
        public int quantity_plan { get; set; }
        public int quantity_in { get; set; }
        public int quantity_used { get; set; }
        public int quantity_out { get; set; }
        public string equipmentId { get; set; }
    
        public virtual BigMaintainDetail BigMaintainDetail { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
