//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraRepairDetail
    {
        public int documentary_id { get; set; }
        public string room_id { get; set; }
        public int broken_camera_quantity { get; set; }
        public string repair_requirement { get; set; }
        public string note { get; set; }
        public int Documentary_camera_repair_status { get; set; }
        public string department_id { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Department Department { get; set; }
        public virtual Documentary Documentary { get; set; }
    }
}
