//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMaintenance
    {
        public CarMaintenance()
        {
            this.CarMaintenanceDetails = new HashSet<CarMaintenanceDetail>();
        }
    
        public int maintainid { get; set; }
        public string equipmentid { get; set; }
        public System.DateTime date { get; set; }
        public string departmentid { get; set; }
        public string maintain_content { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ICollection<CarMaintenanceDetail> CarMaintenanceDetails { get; set; }
        public virtual Department Department { get; set; }
    }
}
