//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public Decision()
        {
            this.Recruitments = new HashSet<Recruitment>();
            this.Terminations = new HashSet<Termination>();
            this.Transfers = new HashSet<Transfer>();
        }
    
        public int decision_id { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<Recruitment> Recruitments { get; set; }
        public virtual ICollection<Termination> Terminations { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
    }
}
