//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentAttendanceAndProductivity
    {
        public int header_attendance_and_productivity_id { get; set; }
        public string total_effort { get; set; }
        public string total_mined_coal { get; set; }
        public string total_mined_meter { get; set; }
        public string total_cropped_meter { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_filled_from_api { get; set; }
        public string department_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual HeaderAttendanceAndProductivity HeaderAttendanceAndProductivity { get; set; }
    }
}
