//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Rooms = new HashSet<Room>();
            this.BigMaintainDetails = new HashSet<BigMaintainDetail>();
            this.CameraRepairDetails = new HashSet<CameraRepairDetail>();
            this.Documentaries = new HashSet<Documentary>();
            this.ImproveDetails = new HashSet<ImproveDetail>();
            this.LiquidationDetails = new HashSet<LiquidationDetail>();
            this.MaintainDetails = new HashSet<MaintainDetail>();
            this.MovelineDetails = new HashSet<MovelineDetail>();
            this.RepairDetails = new HashSet<RepairDetail>();
            this.RevokeDetails = new HashSet<RevokeDetail>();
            this.CarMaintenances = new HashSet<CarMaintenance>();
            this.Equipments = new HashSet<Equipment>();
            this.FuelActivitiesConsumptions = new HashSet<FuelActivitiesConsumption>();
            this.Incident1 = new HashSet<Incident1>();
            this.RepairRegularlies = new HashSet<RepairRegularly>();
            this.DepartmentAttendanceAndProductivities = new HashSet<DepartmentAttendanceAndProductivity>();
            this.HeaderPlanManufacturingByMonths = new HashSet<HeaderPlanManufacturingByMonth>();
            this.HeaderPlanManufacturingByShifts = new HashSet<HeaderPlanManufacturingByShift>();
            this.HeaderPlanManufacturingByYears = new HashSet<HeaderPlanManufacturingByYear>();
            this.HeaderRealityManufacturings = new HashSet<HeaderRealityManufacturing>();
            this.MealRegistrations = new HashSet<MealRegistration>();
            this.Recruitments = new HashSet<Recruitment>();
            this.ReportFiles = new HashSet<ReportFile>();
            this.Consumptions = new HashSet<Consumption>();
            this.MonthlyPlans = new HashSet<MonthlyPlan>();
            this.MonthlyPlans1 = new HashSet<MonthlyPlan>();
            this.Transfers = new HashSet<Transfer>();
            this.Transfers1 = new HashSet<Transfer>();
            this.Employees = new HashSet<Employee>();
        }
    
        public string department_id { get; set; }
        public string department_name { get; set; }
        public string department_type { get; set; }
        public bool isInside { get; set; }
        public Nullable<int> index { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<BigMaintainDetail> BigMaintainDetails { get; set; }
        public virtual ICollection<CameraRepairDetail> CameraRepairDetails { get; set; }
        public virtual ICollection<Documentary> Documentaries { get; set; }
        public virtual ICollection<ImproveDetail> ImproveDetails { get; set; }
        public virtual ICollection<LiquidationDetail> LiquidationDetails { get; set; }
        public virtual ICollection<MaintainDetail> MaintainDetails { get; set; }
        public virtual ICollection<MovelineDetail> MovelineDetails { get; set; }
        public virtual ICollection<RepairDetail> RepairDetails { get; set; }
        public virtual ICollection<RevokeDetail> RevokeDetails { get; set; }
        public virtual ICollection<CarMaintenance> CarMaintenances { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<FuelActivitiesConsumption> FuelActivitiesConsumptions { get; set; }
        public virtual ICollection<Incident1> Incident1 { get; set; }
        public virtual ICollection<RepairRegularly> RepairRegularlies { get; set; }
        public virtual ICollection<DepartmentAttendanceAndProductivity> DepartmentAttendanceAndProductivities { get; set; }
        public virtual ICollection<HeaderPlanManufacturingByMonth> HeaderPlanManufacturingByMonths { get; set; }
        public virtual ICollection<HeaderPlanManufacturingByShift> HeaderPlanManufacturingByShifts { get; set; }
        public virtual ICollection<HeaderPlanManufacturingByYear> HeaderPlanManufacturingByYears { get; set; }
        public virtual ICollection<HeaderRealityManufacturing> HeaderRealityManufacturings { get; set; }
        public virtual ICollection<MealRegistration> MealRegistrations { get; set; }
        public virtual ICollection<Recruitment> Recruitments { get; set; }
        public virtual ICollection<ReportFile> ReportFiles { get; set; }
        public virtual ICollection<Consumption> Consumptions { get; set; }
        public virtual ICollection<MonthlyPlan> MonthlyPlans { get; set; }
        public virtual ICollection<MonthlyPlan> MonthlyPlans1 { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual ICollection<Transfer> Transfers1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
