//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentary
    {
        public Documentary()
        {
            this.Acceptances = new HashSet<Acceptance>();
            this.BigMaintainDetails = new HashSet<BigMaintainDetail>();
            this.CameraRepairDetails = new HashSet<CameraRepairDetail>();
            this.Acceptance1 = new HashSet<Acceptance1>();
            this.LiquidationDetails = new HashSet<LiquidationDetail>();
            this.MaintainDetails = new HashSet<MaintainDetail>();
            this.MovelineDetails = new HashSet<MovelineDetail>();
            this.RepairDetails = new HashSet<RepairDetail>();
            this.RevokeDetails = new HashSet<RevokeDetail>();
            this.Important_Documentary = new HashSet<Important_Documentary>();
            this.ImproveDetails = new HashSet<ImproveDetail>();
            this.RepairCameras = new HashSet<RepairCamera>();
        }
    
        public int documentary_id { get; set; }
        public string documentary_code { get; set; }
        public int documentary_type { get; set; }
        public string department_id_to { get; set; }
        public System.DateTime date_created { get; set; }
        public string person_created { get; set; }
        public string reason { get; set; }
        public string out_in_come { get; set; }
        public int documentary_status { get; set; }
    
        public virtual ICollection<Acceptance> Acceptances { get; set; }
        public virtual ICollection<BigMaintainDetail> BigMaintainDetails { get; set; }
        public virtual ICollection<CameraRepairDetail> CameraRepairDetails { get; set; }
        public virtual ICollection<Acceptance1> Acceptance1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual DocumentaryType DocumentaryType { get; set; }
        public virtual ICollection<LiquidationDetail> LiquidationDetails { get; set; }
        public virtual ICollection<MaintainDetail> MaintainDetails { get; set; }
        public virtual ICollection<MovelineDetail> MovelineDetails { get; set; }
        public virtual ICollection<RepairDetail> RepairDetails { get; set; }
        public virtual ICollection<RevokeDetail> RevokeDetails { get; set; }
        public virtual ICollection<Important_Documentary> Important_Documentary { get; set; }
        public virtual ICollection<ImproveDetail> ImproveDetails { get; set; }
        public virtual ICollection<RepairCamera> RepairCameras { get; set; }
    }
}
