//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendanceAndProductivity
    {
        public string employee_id { get; set; }
        public int header_attendance_and_productivity_id { get; set; }
        public Nullable<System.DateTime> real_time_attendance { get; set; }
        public string productivity_point { get; set; }
        public Nullable<bool> do_work { get; set; }
        public string note { get; set; }
        public Nullable<int> absence_reason_id { get; set; }
        public Nullable<System.DateTime> down_time { get; set; }
        public Nullable<System.DateTime> up_time { get; set; }
        public Nullable<bool> is_changed_manually { get; set; }
        public Nullable<int> actual_header_fetched { get; set; }
        public Nullable<bool> is_filled_from_api { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual AbsenceReason AbsenceReason { get; set; }
        public virtual HeaderAttendanceAndProductivity HeaderAttendanceAndProductivity { get; set; }
        public virtual HeaderAttendanceAndProductivity HeaderAttendanceAndProductivity1 { get; set; }
    }
}
