//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTask
    {
        public string employee_id { get; set; }
        public int task_id { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public Nullable<bool> is_in_process { get; set; }
        public Nullable<bool> is_updated { get; set; }
        public Nullable<System.DateTime> last_time_updated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
