//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderPlanManufacturingByShift
    {
        public HeaderPlanManufacturingByShift()
        {
            this.PlanManufacturingByShifts = new HashSet<PlanManufacturingByShift>();
        }
    
        public int header_phan_manufacturing_by_shifts_id { get; set; }
        public string department_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual ICollection<PlanManufacturingByShift> PlanManufacturingByShifts { get; set; }
    }
}
