//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident1
    {
        public int incident_id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string detail_location { get; set; }
        public string reason { get; set; }
        public string equipmentId { get; set; }
        public string department_id { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Department Department { get; set; }
    }
}
