//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealRegistration
    {
        public int id { get; set; }
        public string department_id { get; set; }
        public System.DateTime date_regs { get; set; }
        public Nullable<int> num_regs { get; set; }
        public Nullable<int> num_regs_plan { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
