//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureUnit
    {
        public MeasureUnit()
        {
            this.Criteria = new HashSet<Criterion>();
        }
    
        public int measure_unit_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Criterion> Criteria { get; set; }
    }
}
