//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Account_Right = new HashSet<Account_Right>();
        }
    
        public string ID { get; set; }
        public string Module1 { get; set; }
    
        public virtual ICollection<Account_Right> Account_Right { get; set; }
    }
}
