//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id_noti { get; set; }
        public int id_problem { get; set; }
        public string department_id { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public bool isread { get; set; }
    }
}
