//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperType
    {
        public PaperType()
        {
            this.Papers = new HashSet<Paper>();
        }
    
        public int paper_type_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_trained_paper { get; set; }
    
        public virtual ICollection<Paper> Papers { get; set; }
    }
}
