//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTable
    {
        public PayTable()
        {
            this.Salaries = new HashSet<Salary>();
            this.Works = new HashSet<Work>();
        }
    
        public int pay_table_id { get; set; }
        public string pay_table { get; set; }
        public string applied_year { get; set; }
    
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual ICollection<Work> Works { get; set; }
    }
}
