//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanManufacturingMonthInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanManufacturingMonthInformation()
        {
            this.HeaderPlanManufacturingByMonths = new HashSet<HeaderPlanManufacturingByMonth>();
        }
    
        public int plan_manufacturing_month_information_id { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string number_working_days { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderPlanManufacturingByMonth> HeaderPlanManufacturingByMonths { get; set; }
    }
}
