//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public Qualification()
        {
            this.RecordPapers = new HashSet<RecordPaper>();
            this.Recruitments = new HashSet<Recruitment>();
        }
    
        public string qualification_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<RecordPaper> RecordPapers { get; set; }
        public virtual ICollection<Recruitment> Recruitments { get; set; }
    }
}
