//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuangHanhManufacturingEntities : DbContext
    {
        public QuangHanhManufacturingEntities()
            : base("name=QuangHanhManufacturingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Account_Right> Account_Right { get; set; }
        public DbSet<Account_Right_Detail> Account_Right_Detail { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Acceptance> Acceptances { get; set; }
        public DbSet<Incident> Incidents { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Supply_DiKem> Supply_DiKem { get; set; }
        public DbSet<Supply_Equipment_DiKem> Supply_Equipment_DiKem { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Vattu_Dikem> Vattu_Dikem { get; set; }
        public DbSet<BigMaintainDetail> BigMaintainDetails { get; set; }
        public DbSet<CameraRepairDetail> CameraRepairDetails { get; set; }
        public DbSet<Documentary> Documentaries { get; set; }
        public DbSet<DocumentaryType> DocumentaryTypes { get; set; }
        public DbSet<Important_Documentary> Important_Documentary { get; set; }
        public DbSet<ImproveDetail> ImproveDetails { get; set; }
        public DbSet<LiquidationDetail> LiquidationDetails { get; set; }
        public DbSet<MaintainDetail> MaintainDetails { get; set; }
        public DbSet<MovelineDetail> MovelineDetails { get; set; }
        public DbSet<RepairDetail> RepairDetails { get; set; }
        public DbSet<RevokeDetail> RevokeDetails { get; set; }
        public DbSet<Acceptance1> Acceptance1 { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<CarGP> CarGPS { get; set; }
        public DbSet<CarMaintenance> CarMaintenances { get; set; }
        public DbSet<CarMaintenanceDetail> CarMaintenanceDetails { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CategoryAttribute> CategoryAttributes { get; set; }
        public DbSet<CategoryAttributeValue> CategoryAttributeValues { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<FuelActivitiesConsumption> FuelActivitiesConsumptions { get; set; }
        public DbSet<Incident1> Incident1 { get; set; }
        public DbSet<Inspection> Inspections { get; set; }
        public DbSet<Insurance> Insurances { get; set; }
        public DbSet<RepairRegularly> RepairRegularlies { get; set; }
        public DbSet<RepairRegularlyDetail> RepairRegularlyDetails { get; set; }
        public DbSet<Status1> Status1 { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<UserActionLog> UserActionLogs { get; set; }
        public DbSet<AdditionalHistoryResume> AdditionalHistoryResumes { get; set; }
        public DbSet<Career> Careers { get; set; }
        public DbSet<Decision> Decisions { get; set; }
        public DbSet<DurationType> DurationTypes { get; set; }
        public DbSet<EducationLevel> EducationLevels { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeTask> EmployeeTasks { get; set; }
        public DbSet<Family> Families { get; set; }
        public DbSet<FamilyRelationship> FamilyRelationships { get; set; }
        public DbSet<FamilyType> FamilyTypes { get; set; }
        public DbSet<Paper> Papers { get; set; }
        public DbSet<PaperStorageType> PaperStorageTypes { get; set; }
        public DbSet<PaperType> PaperTypes { get; set; }
        public DbSet<PayRate> PayRates { get; set; }
        public DbSet<PayTable> PayTables { get; set; }
        public DbSet<Qualification> Qualifications { get; set; }
        public DbSet<Record> Records { get; set; }
        public DbSet<RecordGettingAuthorize> RecordGettingAuthorizes { get; set; }
        public DbSet<RecordPaper> RecordPapers { get; set; }
        public DbSet<RecordStatu> RecordStatus { get; set; }
        public DbSet<Recruitment> Recruitments { get; set; }
        public DbSet<Salary> Salaries { get; set; }
        public DbSet<SalaryProcess> SalaryProcesses { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Specialization> Specializations { get; set; }
        public DbSet<StatusEmployee> StatusEmployees { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TaskType> TaskTypes { get; set; }
        public DbSet<Termination> Terminations { get; set; }
        public DbSet<TerminationType> TerminationTypes { get; set; }
        public DbSet<Transfer> Transfers { get; set; }
        public DbSet<Work> Works { get; set; }
        public DbSet<WorkGroup> WorkGroups { get; set; }
        public DbSet<WorkingProcess> WorkingProcesses { get; set; }
        public DbSet<AbsenceReason> AbsenceReasons { get; set; }
        public DbSet<AbsenceReasonType> AbsenceReasonTypes { get; set; }
        public DbSet<Criterion> Criteria { get; set; }
        public DbSet<CriteriaGroup> CriteriaGroups { get; set; }
        public DbSet<DepartmentAttendanceAndProductivity> DepartmentAttendanceAndProductivities { get; set; }
        public DbSet<EmployeeAttendanceAndProductivity> EmployeeAttendanceAndProductivities { get; set; }
        public DbSet<FakeAPI> FakeAPIs { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<HeaderAttendanceAndProductivity> HeaderAttendanceAndProductivities { get; set; }
        public DbSet<HeaderPlanManufacturingByMonth> HeaderPlanManufacturingByMonths { get; set; }
        public DbSet<HeaderPlanManufacturingByShift> HeaderPlanManufacturingByShifts { get; set; }
        public DbSet<HeaderPlanManufacturingByYear> HeaderPlanManufacturingByYears { get; set; }
        public DbSet<HeaderRealityManufacturing> HeaderRealityManufacturings { get; set; }
        public DbSet<MealRegistration> MealRegistrations { get; set; }
        public DbSet<MeasureUnit> MeasureUnits { get; set; }
        public DbSet<PlanManufacturingByMonth> PlanManufacturingByMonths { get; set; }
        public DbSet<PlanManufacturingByShift> PlanManufacturingByShifts { get; set; }
        public DbSet<PlanManufacturingByYear> PlanManufacturingByYears { get; set; }
        public DbSet<PlanManufacturingMonthInformation> PlanManufacturingMonthInformations { get; set; }
        public DbSet<RealityManufacturingDayInformation> RealityManufacturingDayInformations { get; set; }
        public DbSet<ReportFile> ReportFiles { get; set; }
        public DbSet<SafetyWork> SafetyWorks { get; set; }
        public DbSet<SafetyWorkType> SafetyWorkTypes { get; set; }
        public DbSet<Shift> Shifts { get; set; }
        public DbSet<BigMaintainEquipment> BigMaintainEquipments { get; set; }
        public DbSet<Consumption> Consumptions { get; set; }
        public DbSet<ImproveEquipment> ImproveEquipments { get; set; }
        public DbSet<MaintainEquipment> MaintainEquipments { get; set; }
        public DbSet<MonthlyPlan> MonthlyPlans { get; set; }
        public DbSet<RepairCamera> RepairCameras { get; set; }
        public DbSet<RepairEquipment> RepairEquipments { get; set; }
        public DbSet<RepairRegularly1> RepairRegularly1 { get; set; }
        public DbSet<Supply> Supplies { get; set; }
    }
}
