//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealityManufacturingDayInformation
    {
        public RealityManufacturingDayInformation()
        {
            this.HeaderRealityManufacturings = new HashSet<HeaderRealityManufacturing>();
        }
    
        public int reality_manufacturing_day_information_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string no_date_manufacturing { get; set; }
    
        public virtual ICollection<HeaderRealityManufacturing> HeaderRealityManufacturings { get; set; }
    }
}
