//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public Record()
        {
            this.AdditionalHistoryResumes = new HashSet<AdditionalHistoryResume>();
            this.RecordGettingAuthorizes = new HashSet<RecordGettingAuthorize>();
            this.RecordPapers = new HashSet<RecordPaper>();
        }
    
        public int record_id { get; set; }
        public Nullable<int> record_status_id { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string delivery_employee_id { get; set; }
        public string handover_employee_id { get; set; }
        public string management_employee_id { get; set; }
        public string employee_id { get; set; }
    
        public virtual ICollection<AdditionalHistoryResume> AdditionalHistoryResumes { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual ICollection<RecordGettingAuthorize> RecordGettingAuthorizes { get; set; }
        public virtual ICollection<RecordPaper> RecordPapers { get; set; }
    }
}
