//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int decision_id { get; set; }
        public string employee_id { get; set; }
        public Nullable<System.DateTime> recruitment_date { get; set; }
        public Nullable<int> work_id { get; set; }
        public string department_id { get; set; }
        public string qualification_id { get; set; }
        public Nullable<int> specializations_id { get; set; }
        public Nullable<int> salary_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual Work Work { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
