//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepairRegularly1
    {
        public int supply_sctx_id { get; set; }
        public string supply_id { get; set; }
        public string equipmentId { get; set; }
        public int quantity { get; set; }
        public string equipmentId_dikem { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual Equipment Equipment2 { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
