//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.FakeAPIs = new HashSet<FakeAPI>();
            this.HeaderAttendanceAndProductivities = new HashSet<HeaderAttendanceAndProductivity>();
            this.HeaderPlanManufacturingByShifts = new HashSet<HeaderPlanManufacturingByShift>();
            this.HeaderRealityManufacturings = new HashSet<HeaderRealityManufacturing>();
            this.ReportFiles = new HashSet<ReportFile>();
            this.SafetyWorks = new HashSet<SafetyWork>();
        }
    
        public int shift_id { get; set; }
        public string name { get; set; }
        public Nullable<int> time_start { get; set; }
        public Nullable<int> time_end { get; set; }
    
        public virtual ICollection<FakeAPI> FakeAPIs { get; set; }
        public virtual ICollection<HeaderAttendanceAndProductivity> HeaderAttendanceAndProductivities { get; set; }
        public virtual ICollection<HeaderPlanManufacturingByShift> HeaderPlanManufacturingByShifts { get; set; }
        public virtual ICollection<HeaderRealityManufacturing> HeaderRealityManufacturings { get; set; }
        public virtual ICollection<ReportFile> ReportFiles { get; set; }
        public virtual ICollection<SafetyWork> SafetyWorks { get; set; }
    }
}
