//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        public Specialization()
        {
            this.RecordPapers = new HashSet<RecordPaper>();
            this.Recruitments = new HashSet<Recruitment>();
        }
    
        public int specialization_id { get; set; }
        public string specialization_number { get; set; }
        public string name { get; set; }
        public string career_id { get; set; }
        public Nullable<int> education_level_id { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual ICollection<RecordPaper> RecordPapers { get; set; }
        public virtual ICollection<Recruitment> Recruitments { get; set; }
    }
}
