//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status1
    {
        public Status1()
        {
            this.Equipments = new HashSet<Equipment>();
        }
    
        public int statusid { get; set; }
        public string statusname { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
