//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH_MANUFACTURING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskType
    {
        public TaskType()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int task_type_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
