//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentary_big_maintainance_details
    {
        public string documentary_id { get; set; }
        public string equipment_id { get; set; }
        public string type { get; set; }
        public string remodel_type { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string next_remodel_type { get; set; }
        public Nullable<double> next_end_time { get; set; }
    
        public virtual Documentary Documentary { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
