//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentary()
        {
            this.documentary_big_maintainance_details = new HashSet<documentary_big_maintainance_details>();
            this.documentary_Inspection_details = new HashSet<documentary_Inspection_details>();
            this.documentary_liquidation_details = new HashSet<documentary_liquidation_details>();
            this.documentary_maintain_details = new HashSet<documentary_maintain_details>();
            this.documentary_moveline_details = new HashSet<documentary_moveline_details>();
            this.documentary_repair_details = new HashSet<documentary_repair_details>();
            this.documentary_revoke_details = new HashSet<documentary_revoke_details>();
            this.Supply_plan = new HashSet<Supply_plan>();
        }
    
        public string documentary_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> person_created { get; set; }
        public string reason { get; set; }
        public string type { get; set; }
        public string out_come { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_big_maintainance_details> documentary_big_maintainance_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_Inspection_details> documentary_Inspection_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_liquidation_details> documentary_liquidation_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_maintain_details> documentary_maintain_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_moveline_details> documentary_moveline_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_repair_details> documentary_repair_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_revoke_details> documentary_revoke_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_plan> Supply_plan { get; set; }
    }
}
