//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.documentary_big_maintainance_details = new HashSet<documentary_big_maintainance_details>();
            this.documentary_Inspection_details = new HashSet<documentary_Inspection_details>();
            this.documentary_liquidation_details = new HashSet<documentary_liquidation_details>();
            this.documentary_maintain_details = new HashSet<documentary_maintain_details>();
            this.documentary_moveline_details = new HashSet<documentary_moveline_details>();
            this.documentary_repair_details = new HashSet<documentary_repair_details>();
            this.documentary_revoke_details = new HashSet<documentary_revoke_details>();
            this.equipment_incident = new HashSet<equipment_incident>();
            this.attributes = new HashSet<attribute>();
            this.Supplies = new HashSet<Supply>();
        }
    
        public string equipmentId { get; set; }
        public string equipment_category_id { get; set; }
        public string equipment_name { get; set; }
        public string department_id { get; set; }
        public string supplier { get; set; }
        public Nullable<System.DateTime> date_import { get; set; }
        public Nullable<int> depreciation_estimate { get; set; }
        public Nullable<int> depreciation_present { get; set; }
        public Nullable<System.DateTime> durationOfInspection { get; set; }
        public Nullable<System.DateTime> durationOfInsurance { get; set; }
        public Nullable<System.DateTime> usedDay { get; set; }
        public Nullable<System.DateTime> nearest_Maintenance_Day { get; set; }
        public Nullable<int> total_operating_hours { get; set; }
        public string current_Status { get; set; }
        public Nullable<int> fabrication_number { get; set; }
        public string quality_type { get; set; }
        public string input_channel { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_big_maintainance_details> documentary_big_maintainance_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_Inspection_details> documentary_Inspection_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_liquidation_details> documentary_liquidation_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_maintain_details> documentary_maintain_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_moveline_details> documentary_moveline_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_repair_details> documentary_repair_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentary_revoke_details> documentary_revoke_details { get; set; }
        public virtual Equipment_category Equipment_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_incident> equipment_incident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attribute> attributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}
