//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_incident
    {
        public string equipment_id { get; set; }
        public string incident_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public string reason { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Incident Incident { get; set; }
    }
}
