//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public bool CDVT { get; set; }
        public bool TCLD { get; set; }
        public bool BGD { get; set; }
        public bool DK { get; set; }
        public bool KCS { get; set; }
        public bool PXKT { get; set; }
        public bool ADMIN { get; set; }
    }
}
