//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Right
    {
        public int ID { get; set; }
        public string ModuleID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Right { get; set; }
        public Nullable<bool> isBasic { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
