//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int activity_id { get; set; }
        public string activity_name { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<int> hours_per_day { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string equipmentId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
