//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangCap()
        {
            this.ChiTiet_BangCap = new HashSet<ChiTiet_BangCap>();
        }
    
        public Nullable<int> MaTruong { get; set; }
        public Nullable<int> MaChuyenNghanh { get; set; }
        public int MaBangCap { get; set; }
        public Nullable<int> MaTrinhDo { get; set; }
        public string KieuBangCap { get; set; }
        public Nullable<double> ThoiHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_BangCap> ChiTiet_BangCap { get; set; }
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        public virtual TrinhDo TrinhDo { get; set; }
        public virtual Truong Truong { get; set; }
    }
}
