//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoFile()
        {
            this.FileBaoCaos = new HashSet<FileBaoCao>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<int> ca { get; set; }
        public string phanxuong_id { get; set; }
        public Nullable<bool> @lock { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileBaoCao> FileBaoCaos { get; set; }
    }
}
