//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigMaintainDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BigMaintainDetail()
        {
            this.BigMaintainEquipments = new HashSet<BigMaintainEquipment>();
        }
    
        public int documentary_big_maintain_id { get; set; }
        public int equipment_big_maintain_status { get; set; }
        public string remodel_type { get; set; }
        public System.DateTime end_date { get; set; }
        public string next_remodel_type { get; set; }
        public double next_end_time { get; set; }
        public int documentary_id { get; set; }
        public string equipmentId { get; set; }
        public string attach_to { get; set; }
        public int quantity { get; set; }
        public string equipment_big_maintain_reason { get; set; }
        public string department_id_from { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BigMaintainEquipment> BigMaintainEquipments { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual Documentary Documentary { get; set; }
    }
}
