//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string equipmentId { get; set; }
        public string sokhung { get; set; }
        public string somay { get; set; }
        public Nullable<bool> GPS { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
