//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_NhiemVu_NhanVien
    {
        public System.DateTime NgayNhanNhiemVu { get; set; }
        public string MaNV { get; set; }
        public int MaNhiemVu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhiemVu NhiemVu { get; set; }
    }
}
