//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_CongViec_NhanVien
    {
        public Nullable<double> HeSo { get; set; }
        public Nullable<double> Bac { get; set; }
        public string ThangLuong { get; set; }
        public Nullable<double> MucLuong { get; set; }
        public string MaNV { get; set; }
        public int MaCongViec { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
