//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_BangCap_GiayChungNhan
    {
        public string SoHieu { get; set; }
        public int MaBangCap_GiayChungNhan { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual BangCap_GiayChungNhan BangCap_GiayChungNhan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
