//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTacAnToan
    {
        public int MaCongTacAnToan { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaPhongBan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> LoaiGhiChu { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
