//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec_NhomCongViec
    {
        public int MaCongViec_NhomCongViec { get; set; }
        public Nullable<int> MaCongViec { get; set; }
        public Nullable<int> MaNhomCongViec { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual NhomCongViec NhomCongViec { get; set; }
    }
}
