//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh_NangSuatLaoDong
    {
        public string MaNV { get; set; }
        public int HeaderID { get; set; }
        public Nullable<System.DateTime> ThoiGianThucTeDiemDanh { get; set; }
        public Nullable<double> DiemLuong { get; set; }
        public Nullable<bool> DiLam { get; set; }
        public string GhiChu { get; set; }
        public string LyDoVangMat { get; set; }
        public Nullable<System.DateTime> ThoiGianXuongLo { get; set; }
        public Nullable<System.DateTime> ThoiGianLenLo { get; set; }
        public bool isChangedManually { get; set; }
        public int ActualHeaderFetched { get; set; }
        public bool isFilledFromAPI { get; set; }
    
        public virtual Header_DiemDanh_NangSuat_LaoDong Header_DiemDanh_NangSuat_LaoDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
