//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh_NangSuatLaoDong
    {
        public string MaNV { get; set; }
        public int HeaderID { get; set; }
        public Nullable<System.DateTime> ThoiGianThucTeDiemDanh { get; set; }
        public Nullable<double> HeSoChiaLuong { get; set; }
        public Nullable<double> DiemLuong { get; set; }
        public string DuBaoNguyCo { get; set; }
        public Nullable<bool> DiLam { get; set; }
        public string GhiChu { get; set; }
        public string LyDoVangMat { get; set; }
        public string GiaiPhapNguyCo { get; set; }
    }
}
