//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuDong_NhanVien
    {
        public int MaQuyetDinh { get; set; }
        public string MaNV { get; set; }
        public string LyDoDieuDong { get; set; }
        public string MaDonViMoi { get; set; }
        public Nullable<int> MaChucVuMoi { get; set; }
        public string MaDonViCu { get; set; }
        public Nullable<int> MaChucVuCu { get; set; }
        public Nullable<int> MaBacLuong_ThangLuong_MucLuongCu { get; set; }
        public Nullable<int> MaBacLuong_ThangLuong_MucLuongMoi { get; set; }
    
        public virtual BacLuong_ThangLuong_MucLuong BacLuong_ThangLuong_MucLuong { get; set; }
        public virtual BacLuong_ThangLuong_MucLuong BacLuong_ThangLuong_MucLuong1 { get; set; }
        public virtual CongViec CongViec { get; set; }
        public virtual CongViec CongViec1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual QuyetDinh QuyetDinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
