//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuDong_NhanVien
    {
        public int MaQuyetDinh { get; set; }
        public string MaNV { get; set; }
        public string LyDoDieuDong { get; set; }
        public string DonViMoi { get; set; }
        public string ChucVuMoi { get; set; }
        public string BacLuongMoi { get; set; }
        public Nullable<double> MucLuongMoi { get; set; }
        public string DonViCu { get; set; }
        public string ChucVuCu { get; set; }
        public string BacLuongCu { get; set; }
        public Nullable<double> MucLuongCu { get; set; }
    
        public virtual QuyetDinh QuyetDinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
