//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuDong_NV
    {
        public string DonViCu { get; set; }
        public string DonViMoi { get; set; }
        public string ChucVuHienTai { get; set; }
        public string ChucVuMoi { get; set; }
        public string ThangLuong { get; set; }
        public Nullable<double> Bac { get; set; }
        public Nullable<double> HeSo { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public string DonViNhan { get; set; }
        public string LyDoChuyen { get; set; }
        public string SoQuyetDinh { get; set; }
        public string MaNV { get; set; }
    
        public virtual QuyetDinh QuyetDinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
