//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disk
    {
        public string camera_id { get; set; }
        public string series { get; set; }
        public string capacity { get; set; }
        public string disk_status { get; set; }
    
        public virtual Camera Camera { get; set; }
    }
}
