//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentary_maintain_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentary_maintain_details()
        {
            this.Supply_Documentary_Maintain_Equipment = new HashSet<Supply_Documentary_Maintain_Equipment>();
        }
    
        public int documentary_maintain_id { get; set; }
        public int equipment_maintain_status { get; set; }
        public string maintain_type { get; set; }
        public System.DateTime finish_date_plan { get; set; }
        public int documentary_id { get; set; }
        public string equipmentId { get; set; }
        public string attach_to { get; set; }
        public int quantity { get; set; }
        public string equipment_maintain_reason { get; set; }
        public string department_id_from { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Documentary Documentary { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Documentary_Maintain_Equipment> Supply_Documentary_Maintain_Equipment { get; set; }
    }
}
