//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Accounts = new HashSet<Account>();
            this.EmployeeAttendanceAndProductivities = new HashSet<EmployeeAttendanceAndProductivity>();
            this.EmployeeTasks = new HashSet<EmployeeTask>();
            this.FakeAPIs = new HashSet<FakeAPI>();
            this.Families = new HashSet<Family>();
            this.Records = new HashSet<Record>();
            this.Records1 = new HashSet<Record>();
            this.Records2 = new HashSet<Record>();
            this.Records3 = new HashSet<Record>();
            this.Recruitments = new HashSet<Recruitment>();
            this.SafetyWorks = new HashSet<SafetyWork>();
            this.SalaryProcesses = new HashSet<SalaryProcess>();
            this.Terminations = new HashSet<Termination>();
            this.Transfers = new HashSet<Transfer>();
            this.WorkingProcesses = new HashSet<WorkingProcess>();
        }
    
        public string employee_id { get; set; }
        public string BASIC_INFO_full_name { get; set; }
        public string BASIC_INFO_gender { get; set; }
        public Nullable<System.DateTime> BASIC_INFO_date_of_birth { get; set; }
        public string BASIC_INFO_place_of_birth { get; set; }
        public string BASIC_INFO_nation { get; set; }
        public string BASIC_INFO_home_town { get; set; }
        public string BASIC_INFO_religion { get; set; }
        public string BASIC_INFO_registered_place_of_permanent_residence { get; set; }
        public string BASIC_INFO_current_residence { get; set; }
        public string BASIC_INFO_phone_number { get; set; }
        public string BASIC_INFO_wounded_class { get; set; }
        public string BASIC_INFO_policy_family_child { get; set; }
        public string BASIC_INFO_identity_card { get; set; }
        public Nullable<System.DateTime> BASIC_INFO_date_of_issuance_of_identity_card { get; set; }
        public string BASIC_INFO_social_insurance_number { get; set; }
        public string RECRUITMENT_profession { get; set; }
        public Nullable<System.DateTime> RECRUITMENT_date { get; set; }
        public string RECRUITMENT_company { get; set; }
        public string JOB_instant_position { get; set; }
        public string JOB_work { get; set; }
        public string JOB_civil_servants { get; set; }
        public string JOB_code_ranks { get; set; }
        public string JOB_pay_rate { get; set; }
        public string JOB_coefficients_salary { get; set; }
        public Nullable<System.DateTime> JOB_date { get; set; }
        public string JOB_position_allowance { get; set; }
        public string JOB_other_allowances { get; set; }
        public string JOB_forte_of_work { get; set; }
        public string ACADEMIC_academic_level { get; set; }
        public string ACADEMIC_highest_qualification { get; set; }
        public string ACADEMIC_political_theory { get; set; }
        public string ACADEMIC_state_management { get; set; }
        public string ACADEMIC_languages { get; set; }
        public string ACADEMIC_information_technology { get; set; }
        public Nullable<System.DateTime> PARTY_day_on_VCP { get; set; }
        public Nullable<System.DateTime> PARTY_official_date { get; set; }
        public Nullable<System.DateTime> PARTY_date_of_joining_political_social_organization { get; set; }
        public Nullable<System.DateTime> PARTY_date_of_enlistment { get; set; }
        public Nullable<System.DateTime> PARTY_date_of_discharge { get; set; }
        public string PARTY_highest_rank { get; set; }
        public string PARTY_highest_achieved_title { get; set; }
        public string EVALUATION_bonus { get; set; }
        public string EVALUATION_discipline { get; set; }
        public string HEALTH_health_condition { get; set; }
        public string HEALTH_height { get; set; }
        public string HEALTH_weight { get; set; }
        public string HEALTH_blood_group { get; set; }
        public string PERSONAL_HISTORY_detail { get; set; }
        public string PERSONAL_HISTORY_related_organization { get; set; }
        public string PERSONAL_HISTORY_relatives { get; set; }
        public Nullable<int> current_employee_status_id { get; set; }
        public string current_department_id { get; set; }
        public Nullable<int> current_salary_id { get; set; }
        public Nullable<int> current_work_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Department Department { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAttendanceAndProductivity> EmployeeAttendanceAndProductivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTask> EmployeeTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakeAPI> FakeAPIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recruitment> Recruitments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafetyWork> SafetyWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryProcess> SalaryProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termination> Terminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingProcess> WorkingProcesses { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual Work Work { get; set; }
    }
}
