//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Category_Supply
    {
        public int ecsId { get; set; }
        public string Equipment_category_id { get; set; }
        public string supply_id { get; set; }
    
        public virtual Equipment_category Equipment_category { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
