//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Acceptances = new HashSet<Acceptance>();
            this.Category_attribute_value = new HashSet<Category_attribute_value>();
            this.Documentary_big_maintain_details = new HashSet<Documentary_big_maintain_details>();
            this.Documentary_Inspection_details = new HashSet<Documentary_Inspection_details>();
            this.Documentary_liquidation_details = new HashSet<Documentary_liquidation_details>();
            this.Documentary_maintain_details = new HashSet<Documentary_maintain_details>();
            this.Documentary_moveline_details = new HashSet<Documentary_moveline_details>();
            this.Documentary_repair_details = new HashSet<Documentary_repair_details>();
            this.Equipment_attribute = new HashSet<Equipment_attribute>();
            this.Fuel_activities_consumption = new HashSet<Fuel_activities_consumption>();
            this.Incidents = new HashSet<Incident>();
            this.Quantity_activities = new HashSet<Quantity_activities>();
            this.Documentaries = new HashSet<Documentary>();
            this.Supplies = new HashSet<Supply>();
        }
        [Display(Name = "Mã thiết bị")]

        public string equipmentId { get; set; }
        [Display(Name = "Tên thiết bị")]
        public string equipment_name { get; set; }
        [Display(Name = "Nước sản xuất")]
        public string supplier { get; set; }
        [Display(Name = "Ngày nhập")]
        public System.DateTime date_import { get; set; }
        [Display(Name = "Khấu hao ước tính")]
        public double depreciation_estimate { get; set; }
        [Display(Name = "Khấu hao hiện tại")]
        public double depreciation_present { get; set; }
        [Display(Name = "Thời điểm kiểm định")]
        public System.DateTime durationOfInspection { get; set; }
        [Display(Name = "Thời hạn bảo hiểm")]
        public System.DateTime durationOfInsurance { get; set; }
        [Display(Name = "Ngày đưa vào sử dụng")]
        public System.DateTime usedDay { get; set; }
        [Display(Name = "Ngày bảo dưỡng gần nhất")]
        public System.DateTime nearest_Maintenance_Day { get; set; }
        [Display(Name = "Tổng thời gian hoạt động")]
        public int total_operating_hours { get; set; }
        [Display(Name = "Tình trạng hiện tại")]
        public string current_Status { get; set; }
        [Display(Name = "Số chế tạo")]
        public Nullable<double> fabrication_number { get; set; }
        [Display(Name = "Số hiệu")]
        public string mark_code { get; set; }
        [Display(Name = "Loại chất lượng")]
        public string quality_type { get; set; }
        [Display(Name = "Đường nhập")]
        public string input_channel { get; set; }
        [Display(Name = "Mã nhóm thiết bị")]
        public string Equipment_category_id { get; set; }
        [Display(Name = "Mã sử dụng")]
        public string department_id { get; set; }
        [NotMapped]
        [Display(Name = "Phân xưởng sử dụng")]
        public string department_name { get; set; }
        [NotMapped]
        [Display(Name = "Nhóm thiết bị")]
        public string category_name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acceptance> Acceptances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_attribute_value> Category_attribute_value { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_big_maintain_details> Documentary_big_maintain_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_Inspection_details> Documentary_Inspection_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_liquidation_details> Documentary_liquidation_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_maintain_details> Documentary_maintain_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_moveline_details> Documentary_moveline_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_repair_details> Documentary_repair_details { get; set; }
        public virtual Equipment_category Equipment_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_attribute> Equipment_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fuel_activities_consumption> Fuel_activities_consumption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quantity_activities> Quantity_activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary> Documentaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}
