//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_attribute
    {
        public string Equipment_attribute_id { get; set; }
        public string Equipment_attribute_name { get; set; }
        public string value { get; set; }
        public string unit { get; set; }
        public string equipmentId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
