//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_SCTX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment_SCTX()
        {
            this.Equipment_SCTX_Detail = new HashSet<Equipment_SCTX_Detail>();
        }
    
        public int maintain_id { get; set; }
        public string equipmentId { get; set; }
        public System.DateTime date { get; set; }
        public string department_id { get; set; }
        public string maintain_content { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_SCTX_Detail> Equipment_SCTX_Detail { get; set; }
    }
}
