//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_SCTX_Detail
    {
        public int maintain_detail_id { get; set; }
        public int maintain_id { get; set; }
        public string supplyid { get; set; }
        public int quantity { get; set; }
        public int supplyStatus { get; set; }
    
        public virtual Equipment_SCTX Equipment_SCTX { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
