//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_category_attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment_category_attribute()
        {
            this.Category_attribute_value = new HashSet<Category_attribute_value>();
        }
    
        public string Equipment_category_attribute_id { get; set; }
        public string Equipment_category_attribute_name { get; set; }
        public string unit { get; set; }
        public string Equipment_category_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_attribute_value> Category_attribute_value { get; set; }
        public virtual Equipment_category Equipment_category { get; set; }
    }
}
