//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileBaoCao
    {
        public int id { get; set; }
        public Nullable<int> baoCaoID { get; set; }
        public string fileName { get; set; }
        public string fileNameDisplay { get; set; }
        public Nullable<int> nguoinhap_id { get; set; }
        public Nullable<System.DateTime> uploadTime { get; set; }
        public string chuthich { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BaoCaoFile BaoCaoFile { get; set; }
    }
}
