//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_DiemDanh_NangSuat_LaoDong_Detail
    {
        public int HeaderID { get; set; }
        public double TotalEffort { get; set; }
        public double ThanThucHien { get; set; }
        public double MetLoThucHien { get; set; }
        public double XenThucHien { get; set; }
        public string GhiChu { get; set; }
        public bool isFilledFromAPI { get; set; }
        public string MaPhongBan { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Header_DiemDanh_NangSuat_LaoDong Header_DiemDanh_NangSuat_LaoDong { get; set; }
    }
}
