//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class header_ThucHienSanXuatNgay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public header_ThucHienSanXuatNgay()
        {
            this.ThucHienSanXuatNgays = new HashSet<ThucHienSanXuatNgay>();
        }
    
        public int MaPhongBan_To { get; set; }
        public System.DateTime Ngay { get; set; }
        public int HeaderID { get; set; }
        public int Ca { get; set; }
        public Nullable<int> NgaySanXuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual To To { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThucHienSanXuatNgay> ThucHienSanXuatNgays { get; set; }
    }
}
