//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderRealityManufacturing
    {
        public int header_reality_manufacturing_id { get; set; }
        public string department_id { get; set; }
        public Nullable<int> reality_manufacturing_day_information_id { get; set; }
        public Nullable<int> shift_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual RealityManufacturingDayInformation RealityManufacturingDayInformation { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
