//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderPlanManufacturingByMonth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderPlanManufacturingByMonth()
        {
            this.PlanManufacturingByMonths = new HashSet<PlanManufacturingByMonth>();
        }
    
        public int header_plan_manufacturing_by_month_id { get; set; }
        public string department_id { get; set; }
        public Nullable<int> plan_manufacturing_month_information_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual PlanManufacturingMonthInformation PlanManufacturingMonthInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanManufacturingByMonth> PlanManufacturingByMonths { get; set; }
    }
}
