//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_DiemDanh_NangSuat_LaoDong
    {
        public int HeaderID { get; set; }
        public int Ca { get; set; }
        public string MaPhongBan { get; set; }
        public System.DateTime NgayDiemDanh { get; set; }
        public double TotalEffort { get; set; }
        public bool isFilledFromAPI { get; set; }
    }
}
