//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class header_KeHoachSanXuatNgay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public header_KeHoachSanXuatNgay()
        {
            this.KeHoachSanXuatNgays = new HashSet<KeHoachSanXuatNgay>();
        }
    
        public int HeaderID { get; set; }
        public Nullable<int> MaPhongBan_To { get; set; }
        public Nullable<int> Ca { get; set; }
        public Nullable<System.DateTime> NgayNhapKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachSanXuatNgay> KeHoachSanXuatNgays { get; set; }
        public virtual To To { get; set; }
    }
}
