//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class header_KeHoachSanXuatThang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public header_KeHoachSanXuatThang()
        {
            this.KeHoachSanXuatThangs = new HashSet<KeHoachSanXuatThang>();
        }
    
        public int HeaderID { get; set; }
        public Nullable<int> MaPhongBan_To { get; set; }
        public Nullable<int> ThangKeHoach { get; set; }
        public Nullable<int> NamKeHoach { get; set; }
        public Nullable<int> SoNgayLamViec { get; set; }
        public string GhiChu { get; set; }
    
        public virtual To To { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachSanXuatThang> KeHoachSanXuatThangs { get; set; }
    }
}
