//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int inspect_id { get; set; }
        public string equipment_id { get; set; }
        public System.DateTime inspect_date { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
