//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachTungThang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeHoachTungThang()
        {
            this.header_KeHoachTungThang = new HashSet<header_KeHoachTungThang>();
        }
    
        public int ThangID { get; set; }
        public Nullable<int> ThangKeHoach { get; set; }
        public Nullable<int> NamKeHoach { get; set; }
        public Nullable<int> SoNgayLamViec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<header_KeHoachTungThang> header_KeHoachTungThang { get; set; }
    }
}
