//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoach_TieuChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeHoach_TieuChi()
        {
            this.GhiChus = new HashSet<GhiChu>();
            this.KeHoach_TieuChi_VatLieuSanXuat = new HashSet<KeHoach_TieuChi_VatLieuSanXuat>();
        }
    
        public int MaKeHoach { get; set; }
        public string MaPhongBan { get; set; }
        public int MaTieuChi { get; set; }
        public Nullable<int> ThangKeHoach { get; set; }
        public Nullable<int> NamKeHoach { get; set; }
        public Nullable<int> SoNgayLamViec { get; set; }
        public Nullable<double> SanLuongKeHoach { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GhiChu> GhiChus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoach_TieuChi_VatLieuSanXuat> KeHoach_TieuChi_VatLieuSanXuat { get; set; }
        public virtual TieuChi TieuChi { get; set; }
    }
}
