//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoach_TieuChi_TheoNgay
    {
        public int HeaderID { get; set; }
        public int MaTieuChi { get; set; }
        public Nullable<double> KeHoach { get; set; }
        public System.DateTime ThoiGianNhapCuoiCung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual header_KeHoach_TieuChi_TheoNgay header_KeHoach_TieuChi_TheoNgay { get; set; }
        public virtual TieuChi TieuChi { get; set; }
    }
}
