//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoach_TieuChi_VatLieuSanXuat
    {
        public int MaKeHoach { get; set; }
        public int MaTieuChi_VatLieuSanXuat { get; set; }
        public Nullable<double> TietDienDao { get; set; }
    
        public virtual KeHoach_TieuChi KeHoach_TieuChi { get; set; }
        public virtual TieuChi_VatLieuSanXuat TieuChi_VatLieuSanXuat { get; set; }
    }
}
