//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintain_Car_Detail
    {
        public int maintaindetailid { get; set; }
        public int maintainid { get; set; }
        public string supplyid { get; set; }
        public int quantity { get; set; }
        public int supplyType { get; set; }
        public int supplyStatus { get; set; }
    
        public virtual Maintain_Car Maintain_Car { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
