//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintain_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintain_Car()
        {
            this.Maintain_Car_Detail = new HashSet<Maintain_Car_Detail>();
        }
    
        public int maintainid { get; set; }
        public string equipmentid { get; set; }
        public System.DateTime date { get; set; }
        public string departmentid { get; set; }
        public string maintain_content { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintain_Car_Detail> Maintain_Car_Detail { get; set; }
    }
}
