//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPlan
    {
        public int monthly_plan_id { get; set; }
        public string supply_id { get; set; }
        public string department_id { get; set; }
        public string equipment_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> quota { get; set; }
        public int quantity_plan { get; set; }
        public int quantity { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> quantity_provide { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Supply Supply { get; set; }
        public virtual Supply Supply1 { get; set; }
    }
}
