//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiUyQuyenLayHoSo_BaoHiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiUyQuyenLayHoSo_BaoHiem()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaUyQuyen { get; set; }
        public string HoTen { get; set; }
        public string QuanHe { get; set; }
        public string SoCMND { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChiThuongTru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
