//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChamDut_NhanVien = new HashSet<ChamDut_NhanVien>();
            this.ChiTiet_BangCap = new HashSet<ChiTiet_BangCap>();
            this.ChiTiet_CongViec_NhanVien = new HashSet<ChiTiet_CongViec_NhanVien>();
            this.ChungChi_NhanVien = new HashSet<ChungChi_NhanVien>();
            this.DiemDanh_NangSuatLaoDong = new HashSet<DiemDanh_NangSuatLaoDong>();
            this.DieuDong_NV = new HashSet<DieuDong_NV>();
            this.GiayChungNhan_NhanVien = new HashSet<GiayChungNhan_NhanVien>();
            this.GiayToes = new HashSet<GiayTo>();
            this.ChiTiet_NhiemVu_NhanVien = new HashSet<ChiTiet_NhiemVu_NhanVien>();
            this.QuanHeGiaDinhs = new HashSet<QuanHeGiaDinh>();
            this.QuaTrinhCongTacs = new HashSet<QuaTrinhCongTac>();
        }
        [Display(Name = "Mã Nhân Viên")]
        public string MaNV { get; set; }
        [Display(Name = "Tên")]
        public string Ten { get; set; }
        [Display(Name = "Tên Khác")]
        public string Tenkhac { get; set; }
        [Display(Name = "Giới tính")]
        public bool GioiTinh { get; set; }
        [Display(Name = "Cấp ủy hiện tại")]
        public string CapUyHienTai { get; set; }
        [Display(Name = "Cấp ủy kiêm")]
        public string CapUyKiem { get; set; }
        [Display(Name = "Chức vụ")]
        public string ChucVu { get; set; }
        [Display(Name = "Phụ cấp chức vụ")]
        public Nullable<double> PhuCapChucVu { get; set; }
        [Display(Name = "Ngày sinh")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Display(Name = "Nơi sinh")]
        public string NoiSinh { get; set; }
        [Display(Name = "Dân tộc")]
        public string DanToc { get; set; }
        [Display(Name = "Quê quán")]
        public string QueQuan { get; set; }
        [Display(Name = "Tôn giáo")]
        public string TonGiao { get; set; }
        [Display(Name = "Nơi ở hiện tại")]
        public string NoiOHienTai { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SoDienThoai { get; set; }
        [Display(Name = "Thành phần gia đình xuất thân")]
        public string TPGiaDinhXuatThan { get; set; }
        [Display(Name = "Ngày tham gia cách mạng")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayThamGiaCachMang { get; set; }
        [Display(Name = "Ngày vào đảng")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayVaoDangCSVN { get; set; }
        [Display(Name = "Ngày chính thức")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayChinhThuc { get; set; }
        [Display(Name = "Ngày vào tổ chức CTXH")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayVaoToChucCTXH { get; set; }
        [Display(Name = "Tổ chức")]
        public string ToChuc { get; set; }
        [Display(Name = "Ngày nhập ngũ")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayNhapNgu { get; set; }
        [Display(Name = "Ngày xuất ngũ")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayXuatNgu { get; set; }
        [Display(Name = "Quân hàm chức vụ cao nhất")]
        public string QuanHamChucVuCaoNhat { get; set; }
        [Display(Name = "Trình độ học vấn")]
        public string TrinhDoHocVan { get; set; }
        [Display(Name = "Học hàm học vị cao nhất")]
        public string HocHamHocViCaoNhat { get; set; }
        [Display(Name = "Lý luận chính trị")]
        public string LyLuanChinhTri { get; set; }
        [Display(Name = "Ngoại ngữ")]
        public string NgoaiNgu { get; set; }
        [Display(Name = "Công tác chính đang làm")]
        public string CongTacChinhDangLam { get; set; }
        [Display(Name = "Ngạch công chức")]
        public string NgachCongChuc { get; set; }
        [Display(Name = "Mã ngạch")]
        public Nullable<double> MaNgach { get; set; }
        [Display(Name = "Danh hiệu được phong")]
        public string DanhHieuDuocPhong { get; set; }
        [Display(Name = "Sở trường công tác")]
        public string SoTruongCongTac { get; set; }
        [Display(Name = "Công việc đã làm lâu nhất")]
        public string CongViecDaLamLauNhat { get; set; }
        [Display(Name = "Khen thưởng")]
        public string KhenThuong { get; set; }
        [Display(Name = "Kỷ luật")]
        public string KyLuat { get; set; }
        [Display(Name = "Tình trạng sức khỏe")]
        public string TinhTrangSucKhoe { get; set; }
        [Display(Name = "Chi tiết sức khỏe")]
        public string ChiTietSucKhoe { get; set; }
        [Display(Name = "Chiều cao")]
        public Nullable<double> ChieuCao { get; set; }
        [Display(Name = "Cân nặng")]
        public Nullable<double> CanNang { get; set; }
        [Display(Name = "Nhóm máu")]
        public string NhomMau { get; set; }
        [Display(Name = "Hạng thương binh")]
        public string HangThuongBinh { get; set; }
        [Display(Name = "Gia đình chính sách")]
        public string GiaDinhChinhSach { get; set; }
        [Display(Name = "số CMND")]
        public string SoCMND { get; set; }
        [Display(Name = "Ngày cấp CMND")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayCapCMND { get; set; }
        [Display(Name = "Nơi cấp CMND")]
        public string NoiCapCMND { get; set; }
        [Display(Name = "Ngày đi làm")]
        public string NgayDiLam { get; set; }
        [Display(Name = "Tên phân xưởng")]
        public string TenPhanXuong { get; set; }
        [Display(Name = "Trạng thái làm việc")]
        public string TrangThaiLamViec { get; set; }
        [Display(Name = "Mã phòng ban")]
        public string MaPhongBan { get; set; }
        [Display(Name = "Mã ủy quyền")]
        public Nullable<int> MaUyQuyen { get; set; }
        [Display(Name = "Số BHXH")]
        public string SoBHXH { get; set; }
        [Display(Name = "Ngày trả BHXH")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayTraBHXH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamDut_NhanVien> ChamDut_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_BangCap> ChiTiet_BangCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_CongViec_NhanVien> ChiTiet_CongViec_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChungChi_NhanVien> ChungChi_NhanVien { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh_NangSuatLaoDong> DiemDanh_NangSuatLaoDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DieuDong_NV> DieuDong_NV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiayChungNhan_NhanVien> GiayChungNhan_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiayTo> GiayToes { get; set; }
        public virtual HoSo HoSo { get; set; }
        public virtual NguoiUyQuyenLayHoSo_BaoHiem NguoiUyQuyenLayHoSo_BaoHiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_NhiemVu_NhanVien> ChiTiet_NhiemVu_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanHeGiaDinh> QuanHeGiaDinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhCongTac> QuaTrinhCongTacs { get; set; }
    }
}
