//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan_TieuChi
    {
        public int MaTieuChi { get; set; }
        public string MaPhongBan { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual TieuChi TieuChi { get; set; }
    }
}
