//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantity_activities
    {
        public double quantity { get; set; }
        public string activityid { get; set; }
        public int hours_per_day { get; set; }
        public System.DateTime date { get; set; }
        public string equipmentId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
