//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyetDinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyetDinh()
        {
            this.ChamDut_NhanVien = new HashSet<ChamDut_NhanVien>();
            this.DieuDong_NhanVien = new HashSet<DieuDong_NhanVien>();
        }
    
        public int MaQuyetDinh { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamDut_NhanVien> ChamDut_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DieuDong_NhanVien> DieuDong_NhanVien { get; set; }
    }
}
