//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordGettingAuthorize
    {
        public int record_getting_authorize_id { get; set; }
        public string full_name { get; set; }
        public string identity_card_number { get; set; }
        public string phone_number { get; set; }
        public string permanent_address { get; set; }
        public Nullable<int> record_id { get; set; }
        public Nullable<int> family_relationship_id { get; set; }
    
        public virtual FamilyRelationship FamilyRelationship { get; set; }
        public virtual Record Record { get; set; }
    }
}
