//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.AdditionalHistoryResumes = new HashSet<AdditionalHistoryResume>();
            this.RecordsGettingAuthorizes = new HashSet<RecordsGettingAuthorize>();
            this.RecordsPapers = new HashSet<RecordsPaper>();
        }
    
        public int records_id { get; set; }
        public Nullable<int> records_status_id { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string delivery_employee_id { get; set; }
        public string handover_employee_id { get; set; }
        public string management_employee_id { get; set; }
        public string employee_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalHistoryResume> AdditionalHistoryResumes { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual RecordsStatu RecordsStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordsGettingAuthorize> RecordsGettingAuthorizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordsPaper> RecordsPapers { get; set; }
    }
}
