//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Acceptances = new HashSet<Acceptance>();
            this.Incidents = new HashSet<Incident>();
            this.CameraRepairDetails = new HashSet<CameraRepairDetail>();
            this.RepairCameras = new HashSet<RepairCamera>();
            this.Status = new HashSet<Status>();
        }
    
        public string department_id { get; set; }
        public string room_id { get; set; }
        public string room_name { get; set; }
        public int camera_quantity { get; set; }
        public int camera_available { get; set; }
        public string series { get; set; }
        public string capacity { get; set; }
        public string disk_status { get; set; }
        public string signal_loss_reason { get; set; }
        public string note { get; set; }
        public bool disk_saveable { get; set; }
        public string login_information { get; set; }
        public string image_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acceptance> Acceptances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CameraRepairDetail> CameraRepairDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairCamera> RepairCameras { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
    }
}
