//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Camera_Acceptance = new HashSet<Camera_Acceptance>();
            this.CameraIncidents = new HashSet<CameraIncident>();
            this.Documentary_camera_repair_details = new HashSet<Documentary_camera_repair_details>();
            this.Supply_Documentary_Camera = new HashSet<Supply_Documentary_Camera>();
        }
    
        public string department_id { get; set; }
        public int room_id { get; set; }
        public string room_name { get; set; }
        public int camera_quantity { get; set; }
        public int camera_available { get; set; }
        public string series { get; set; }
        public string capacity { get; set; }
        public string disk_status { get; set; }
        public string signal_loss_reason { get; set; }
        public string note { get; set; }
        public bool disk_saveable { get; set; }
        public string login_information { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camera_Acceptance> Camera_Acceptance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CameraIncident> CameraIncidents { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentary_camera_repair_details> Documentary_camera_repair_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Documentary_Camera> Supply_Documentary_Camera { get; set; }
    }
}
