//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucHienTheoNgay
    {
        public int HeaderID { get; set; }
        public System.DateTime Ngay { get; set; }
        public int Ca { get; set; }
        public Nullable<int> NgaySanXuat { get; set; }
    
        public virtual header_ThucHienTheoNgay header_ThucHienTheoNgay { get; set; }
    }
}
