//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucHienTheoNgay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucHienTheoNgay()
        {
            this.header_ThucHienTheoNgay = new HashSet<header_ThucHienTheoNgay>();
        }
    
        public int NgayID { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<int> NgaySanXuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<header_ThucHienTheoNgay> header_ThucHienTheoNgay { get; set; }
    }
}
