//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucHienSanXuatNgay
    {
        public int HeaderID { get; set; }
        public int MaTieuChiCon { get; set; }
        public Nullable<double> SanLuong { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaVatLieu { get; set; }
    
        public virtual header_ThucHienSanXuatNgay header_ThucHienSanXuatNgay { get; set; }
        public virtual VatLieu VatLieu { get; set; }
        public virtual TieuChiCon TieuChiCon { get; set; }
    }
}
