//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChiCon_Thang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieuChiCon_Thang()
        {
            this.KeHoachSanXuatThangs = new HashSet<KeHoachSanXuatThang>();
        }
    
        public int MaTieuChiCon_Thang { get; set; }
        public string TenTieuChiCon_Thang { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> MaTinhChat_TieuChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachSanXuatThang> KeHoachSanXuatThangs { get; set; }
        public virtual TinhChat_TieuChi TinhChat_TieuChi { get; set; }
    }
}
