//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieuChi()
        {
            this.KeHoachSanXuatNams = new HashSet<KeHoachSanXuatNam>();
            this.PhongBan_TieuChi = new HashSet<PhongBan_TieuChi>();
            this.TinhChat_TieuChi = new HashSet<TinhChat_TieuChi>();
        }
    
        public int MaTieuChi { get; set; }
        public string TenTieuChi { get; set; }
        public string DonViDo { get; set; }
        public Nullable<int> MaNhomTieuChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachSanXuatNam> KeHoachSanXuatNams { get; set; }
        public virtual NhomTieuChi NhomTieuChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongBan_TieuChi> PhongBan_TieuChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhChat_TieuChi> TinhChat_TieuChi { get; set; }
    }
}
