//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhChat_TieuChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinhChat_TieuChi()
        {
            this.TieuChiCon_Thang = new HashSet<TieuChiCon_Thang>();
        }
    
        public int MaTinhChat_TieuChi { get; set; }
        public string TenTinhChat_TieuChi { get; set; }
        public Nullable<int> MaTieuChi { get; set; }
    
        public virtual TieuChi TieuChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TieuChiCon_Thang> TieuChiCon_Thang { get; set; }
    }
}
