//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class To
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public To()
        {
            this.header_KeHoachSanXuatNgay = new HashSet<header_KeHoachSanXuatNgay>();
            this.header_KeHoachSanXuatThang = new HashSet<header_KeHoachSanXuatThang>();
            this.header_ThucHienSanXuatNgay = new HashSet<header_ThucHienSanXuatNgay>();
        }
    
        public int MaTo { get; set; }
        public string TenTo { get; set; }
        public string MaPhongBan { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<header_KeHoachSanXuatNgay> header_KeHoachSanXuatNgay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<header_KeHoachSanXuatThang> header_KeHoachSanXuatThang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<header_ThucHienSanXuatNgay> header_ThucHienSanXuatNgay { get; set; }
    }
}
