//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkWorkGroup
    {
        public int work_work_group_id { get; set; }
        public int work_id { get; set; }
        public int work_group_id { get; set; }
    
        public virtual Work Work { get; set; }
        public virtual WorkGroup WorkGroup { get; set; }
    }
}
