//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANGHANH2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Category_attribute_value = new HashSet<Category_attribute_value>();
            this.Equipment_attribute = new HashSet<Equipment_attribute>();
        }
    
        public string equipmentId { get; set; }
        public string equipment_name { get; set; }
        public string supplier { get; set; }
        public System.DateTime date_import { get; set; }
        public double depreciation_estimate { get; set; }
        public double depreciation_present { get; set; }
        public System.DateTime durationOfInspection { get; set; }
        public System.DateTime durationOfInsurance { get; set; }
        public System.DateTime usedDay { get; set; }
        public System.DateTime nearest_Maintenance_Day { get; set; }
        public int total_operating_hours { get; set; }
        public string current_Status { get; set; }
        public string fabrication_number { get; set; }
        public string quality_type { get; set; }
        public string input_channel { get; set; }
        public string Equipment_category_id { get; set; }
        public string department_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_attribute_value> Category_attribute_value { get; set; }
        public virtual Department Department { get; set; }
        public virtual Equipment_category Equipment_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_attribute> Equipment_attribute { get; set; }
    }
}
